### ISSUE TITLE
Naming conflict

### ISSUE THREAD

**Issue by gdude2002** [zml2008/featherchat#1]
Ohaithar.

> <zml> hey, I noticed you had a chat plugin https://github.com/chatterbox-works/Chatterbox. I also have a chat plugin https://github.com/zml2008/chatterbox with the same name -- I can understand missing that, but would you mind finding a different name for yours -- wouldn't want people to get confused between the two

I'm one of the other team members of Chatterbox - @jkcclemens poked me about this last night and I got it when I got online a few minutes ago.

---

While it does look like your repo is slightly older than ours, please consider the following points.

* This is a very small repo with 16 commits, no issues, no PRs, and limited docs
    * For comparison, our repo has 169 commits, 15 issues, no PRs, and quite a lot of docs
* We've already spent time building a community and some reputation using this name, as well as working on branding, graphical work, and other things. A few examples include:
    * **#chatterbox** over on Esper
    * https://chatterbox.works (and related hosting, SSL, etc)
    * Branded Discourse forum
    * GitHub org (we were quite annoyed when we found a disused [Chatterbox](https://github.com/Chatterbox) user)
    * [WeTranslate project](https://webtranslateit.com/en/projects/11623-Chatterbox)
* When we were first coming up with the name, we did spend a few hours making sure that it wasn't taken, and this repo didn't come up in our searches. I'm not entirely sure whether the repo was private at that point or whether we came up with the name before that.

---

I get it, though. As a programmer, I can say that coming up with a name for a project is one of the most difficult parts of the project. We spent a lot of time on this name, striking off many alternatives, and we've laid groundwork, built foundations and worked around this name, developing quite a lot. In comparison, all I can find for your plugin is this single small repo.

Therefore, I respectfully ask that you either change your project's name, or risk the conflicts. It doesn't make logical sense for us to rebrand, when it isn't really feasible for us, and would be so much easier for you to do so, given the lack of community-building and infrastructure.

I've seen you around Esper and I highly respect your status as a developer. However, this looks like a bad timing coincidence, and while neither you nor our team is at fault, it makes a lot more sense to go down the path that involves the least butchery.

---

Please feel free to discuss here, or create a ticket on our repo if you feel that's more appropriate. We would like to come to a resolution, but the one you've provided just doesn't make sense to us.

**Comment by zml2008** [comment]
nice convo: https://gist.github.com/anonymous/2bea93d6a76db89bdc0c
I'm staying chatterbox. you and your 5 users can deal with that.

**Comment by jkcclemens** [comment]
Well, I'll be the first to admit that our, and mostly my, behavior was inappropriate. If you can understand, I was immensely annoyed at the name conflict, which was just the straw on the camel's back, where the camel was carrying lots of personal issues. Of course, that's no excuse, but it is the main cause behind it.

I hope, also, that you can see where out suspicion came from, as well. I didn't think much of it; it seemed like a low thing to do, and I doubted any developer would steal an idea like that.

I hope my misplaced venting and anger doesn't tarnish your reputation of me, and I deeply regret what I said. I apologize for my actions, of course.

I was never good at apologies, but I hope this suffices. My apologies.

**Comment by gdude2002** [comment]
I have talked to a mutual acquaintance (the one that shared those logs) between now and the above response, and I thought I might as well give my view on this.

As far as I was concerned, after my PM with @zml2008 on IRC, I took him to be an upstanding and mature person. I can say that @jkcclemens isn't generally one to speak out in the form that was quoted in the log. However, I feel like I should add some context to this.

---

So here's the assumptions we had made in the time before and around the log.

* We had come up with the name `Chatterbox` at roughly the same time as @zml2008 had, simply an annoying coincidence.
* @zml2008 was currently in the channel I mentioned using a template engine in. It didn't look fantastic, obviously, but we didn't want to directly point fingers as plagiarism isn't something I'd expect from @zml2008.
    * Yesterday, I learned that @zml2008 had only been in the channel since May 27th and was able to back that up with my own logs. This happened after the above reply, but the fact has helped curb our frustration significantly.
* We were being asked to rename for a project with less than 10% of the work we'd put in, [no visible interest](https://forums.spongepowered.org/t/chatterbox/6886/5), and that had appeared to be an API demo for State Of Sponge.
* It had taken an investment of large amounts of time and some money to set up and learn the nuances of our infrastructure and website.

---

All that considered, can you really blame us for being a little annoyed?

The log supplied to you was in a small channel that contained users that we trusted. Nobody felt the need to say "Look, I'm blowing off steam now, don't send the logs to anyone". I can't apologise on behalf of others, but I have talked to the person that shared the logs, and they have apologised for putting a spanner in the works, so to speak, when there was no need to. People need to vent - it's a fact of life.

I was looking for an amicable, mature solution, and I thought I had had one until the `you and your 5 users can deal with that` response. The way I see it, the following solutions are still in play, however.

* Rename this project
* Merge the projects and combine our expertise

Ignoring the problem isn't a solution - it will cause too much community confusion, and will end up with us stepping on each other's toes as we try to submit our plugins to their relevant plugin repositories.

**Comment by MikaalSky** [comment]
Just leave plugins be. There isnt a copyright or anything on names, and really all it comes down to is which one people like better, so go make your plugin and try to make something better.

**Comment by gdude2002** [comment]
@MikaalSky The problem is that two plugins with naming conflicts will break each other. Also, project names on plugin repo sites would most likely have to be unique as well.

**Comment by modwizcode** [comment]
Well since one of these is sponge only and the other one is currently
bukkit only I don't see a problem.

**Comment by gdude2002** [comment]
@modwizcode Sponge support is planned.

**Comment by modwizcode** [comment]
But currently not supporting sponge and TBH I looked at the code structure and it's not going to be Sponge compatible soon since it's interwoven with Bukkit dependencies. One of you may have to rename, but that will come later.

**Comment by gdude2002** [comment]
@modwizcode Someone will, sure. I don't think deferring the issue is going to help, though. Rebranding is often a huge pain in the ass, and it's much easier and more sensible to get it out of the way earlier.

**Comment by modwizcode** [comment]
I agree, the sooner you rebrand the quicker the conflict that you are creating will be resolved. Nothing is forcing zml to rebrand, you have no trademark. Sure it's better for everyone if he renames, you've put more effort and resources into your project, however it's taking it too far to demand or try and provoke a rebrand.

Do you really want to create more drama in a Minecraft community simply because it would be nice for your project? Or do you want to spend time making a cool plugin with great features?

**Comment by jkcclemens** [comment]
Oh god. This is getting out of hand. I'd like to remind everyone that it was zml that asked us to rebrand in the first place. We didn't step out of bounds by making this issue or asking for an update. At this point, all I want is a response from @zml2008.

**Comment by gdude2002** [comment]
Yeah, it's pretty much as @jkcclemens has said. Aside from one or two people, the only thing I've noticed relating to this is that everyone wants to make life for our project difficult. There was no drama relating to any of this until @zml2008's "nice convo" response. If you're looking to stir the pot, @modwizcode, that's entirely on you.

**Comment by Tzky** [comment]
As an unconcerned observer i'd suggest leaving as it is (zml = sponge; you = Bukkit) OR suggest both projects change their names. Maybe Bukkitchatter and Spongechatter or sth. like that.

I see why zml posted his comment. Telling someone to f* o* isn't nice, regardless if you're telling him directly or if he reads it via logs ;)

**Comment by gdude2002** [comment]
@Tzky I agree with your sentiment RE dealing with people, but I do believe people should be given the chance to vent in stressful situations. If we had that much of an issue with @zml2008, we wouldn't be trying to cooperate with him.

We don't intend on avoiding Sponge, I don't really see that changing. Why limit our horizons?

Personally, I feel that one party renaming, or alternatively both projects merging would be ideal solutions. However, I've been told that ZML wants to think on it, so I was going to just leave my thoughts in the response I made before @MikaalSky's, and wait for a response, instead of bothering him. Either way, we can't know what to do until he responds here, so we're just pressing on.

**Comment by zml2008** [comment]
Ok, you've had your fuck-you moment, I've had my fuck-you moment, but really I think it's time to resolve this and get on with our lives. At this point I'm ok going back to the previous agreement, so I've been thinking about other names & am on the way to getting a new name. I'm reopening this issue and close it with the commit that performs the name change.

**Comment by gdude2002** [comment]
Thanks for reconsidering, and apologies for any offense/trouble caused by this.

I agree with you - I'm glad we can resolve this and move on.

**Comment by zml2008** [comment]
There we go -- if you have any more questions or thoughts, please feel free to contact me on IRC g or jkcclemens -- I'll be locking this issue.
